import * as core from "../../core/lib/render.js";
import { CODEX_PROVIDER } from "./provider-config.js";
export const renderSetupReport = (report) => core.renderSetupReport(CODEX_PROVIDER, report);
export const renderReviewResult = (parsedResult, meta) => core.renderReviewResult(CODEX_PROVIDER, parsedResult, meta);
export const renderNativeReviewResult = (result, meta) => core.renderNativeReviewResult(CODEX_PROVIDER, result, meta);
export const renderTaskResult = (parsedResult, meta) => core.renderTaskResult(CODEX_PROVIDER, parsedResult, meta);
export const renderStatusReport = (report) => core.renderStatusReport(CODEX_PROVIDER, report);
export const renderJobStatusReport = (job) => core.renderJobStatusReport(CODEX_PROVIDER, job);
export const renderStoredJobResult = (job, storedJob) => core.renderStoredJobResult(CODEX_PROVIDER, job, storedJob);
export const renderCancelReport = (job) => core.renderCancelReport(CODEX_PROVIDER, job);
