import * as core from "../../core/lib/state.js";
import { CODEX_PROVIDER } from "./provider-config.js";
export const resolveStateDir = (cwd) => core.resolveStateDir(CODEX_PROVIDER, cwd);
export const resolveStateFile = (cwd) => core.resolveStateFile(CODEX_PROVIDER, cwd);
export const resolveJobsDir = (cwd) => core.resolveJobsDir(CODEX_PROVIDER, cwd);
export const ensureStateDir = (cwd) => core.ensureStateDir(CODEX_PROVIDER, cwd);
export const loadState = (cwd) => core.loadState(CODEX_PROVIDER, cwd);
export const saveState = (cwd, state) => core.saveState(CODEX_PROVIDER, cwd, state);
export const updateState = (cwd, mutate) => core.updateState(CODEX_PROVIDER, cwd, mutate);
export const upsertJob = (cwd, jobPatch) => core.upsertJob(CODEX_PROVIDER, cwd, jobPatch);
export const listJobs = (cwd) => core.listJobs(CODEX_PROVIDER, cwd);
export const setConfig = (cwd, key, value) => core.setConfig(CODEX_PROVIDER, cwd, key, value);
export const getConfig = (cwd) => core.getConfig(CODEX_PROVIDER, cwd);
export const writeJobFile = (cwd, jobId, payload) => core.writeJobFile(CODEX_PROVIDER, cwd, jobId, payload);
export const resolveJobLogFile = (cwd, jobId) => core.resolveJobLogFile(CODEX_PROVIDER, cwd, jobId);
export const resolveJobFile = (cwd, jobId) => core.resolveJobFile(CODEX_PROVIDER, cwd, jobId);
export { generateJobId, readJobFile } from "../../core/lib/state.js";
