import * as core from "../../core/lib/render.js";
import { AGENT_PROVIDER } from "./provider-config.js";
export const renderSetupReport = (report) => core.renderSetupReport(AGENT_PROVIDER, report);
export const renderReviewResult = (parsedResult, meta) => core.renderReviewResult(AGENT_PROVIDER, parsedResult, meta);
export const renderNativeReviewResult = (result, meta) => core.renderNativeReviewResult(AGENT_PROVIDER, result, meta);
export const renderTaskResult = (parsedResult, meta) => core.renderTaskResult(AGENT_PROVIDER, parsedResult, meta);
export const renderStatusReport = (report) => core.renderStatusReport(AGENT_PROVIDER, report);
export const renderJobStatusReport = (job) => core.renderJobStatusReport(AGENT_PROVIDER, job);
export const renderStoredJobResult = (job, storedJob) => core.renderStoredJobResult(AGENT_PROVIDER, job, storedJob);
export const renderCancelReport = (job) => core.renderCancelReport(AGENT_PROVIDER, job);
