import * as core from "../../core/lib/state.js";
import { AGENT_PROVIDER } from "./provider-config.js";
export const resolveStateDir = (cwd) => core.resolveStateDir(AGENT_PROVIDER, cwd);
export const resolveStateFile = (cwd) => core.resolveStateFile(AGENT_PROVIDER, cwd);
export const resolveJobsDir = (cwd) => core.resolveJobsDir(AGENT_PROVIDER, cwd);
export const ensureStateDir = (cwd) => core.ensureStateDir(AGENT_PROVIDER, cwd);
export const loadState = (cwd) => core.loadState(AGENT_PROVIDER, cwd);
export const saveState = (cwd, state) => core.saveState(AGENT_PROVIDER, cwd, state);
export const updateState = (cwd, mutate) => core.updateState(AGENT_PROVIDER, cwd, mutate);
export const upsertJob = (cwd, jobPatch) => core.upsertJob(AGENT_PROVIDER, cwd, jobPatch);
export const listJobs = (cwd) => core.listJobs(AGENT_PROVIDER, cwd);
export const setConfig = (cwd, key, value) => core.setConfig(AGENT_PROVIDER, cwd, key, value);
export const getConfig = (cwd) => core.getConfig(AGENT_PROVIDER, cwd);
export const writeJobFile = (cwd, jobId, payload) => core.writeJobFile(AGENT_PROVIDER, cwd, jobId, payload);
export const resolveJobLogFile = (cwd, jobId) => core.resolveJobLogFile(AGENT_PROVIDER, cwd, jobId);
export const resolveJobFile = (cwd, jobId) => core.resolveJobFile(AGENT_PROVIDER, cwd, jobId);
export { generateJobId, readJobFile } from "../../core/lib/state.js";
